In [17]:
import pandas as pd
import numpy as np

data = {
    'id_pracownika': [1,2,3,4,5,6,7,8,9,10,
                      11,12,13,14,15,16,17,18,19,20,
                      3,7,12,18,5,      # duplikaty — te same id!
                      21,22,23,24,25],
    'imie': ['Anna', 'Bartek', 'CELINA', 'darek', 'Ewa',
             'Filip', 'Gosia', 'HENRYK', 'irena', 'Jan',
             'Kasia', 'Leszek', 'Marta', 'norbert', 'OLGA',
             'Piotr', 'Renata', 'sławek', 'Teresa', 'Urszula',
             'CELINA', 'Gosia', 'Leszek', 'sławek', 'Ewa',
             'Wanda', 'Xawery', 'Yvonne', 'Zbyszek', 'Agata'],
    'dzial': ['Sprzedaz', 'IT', 'HR', 'sprzedaz', 'IT',
              'HR', 'Sprzedaz', 'it', 'HR', 'Sprzedaz',
              'IT', 'HR', 'sprzedaz', 'IT', 'HR',
              'Sprzedaz', 'it', 'HR', 'Sprzedaz', 'IT',
              'HR', 'Sprzedaz', 'HR', 'HR', 'IT',
              'Sprzedaz', 'IT', 'hr', 'Sprzedaz', 'IT'],
    'wynagrodzenie': ['4500', '6200', '3800', '5100', '7500',
                      '4200', '5800', '6900', '3500', '4800',
                      '7200', '4100', '5500', '6800', '3900',
                      '5200', '4700', '6100', '3800', '5400',
                      '3800', '5800', '4100', '6100', '7500',
                      'brak', '5000', None, '4300', '6600'],
    'data_zatrudnienia': ['2020-03-15', '2019-07-22', '2021-01-10',
                          '2018-05-30', '2022-11-01', '2020-08-14',
                          '2019-12-05', '2021-06-18', '2017-09-23',
                          '2023-02-07', '2020-04-11', '2018-11-28',
                          '2022-07-15', '2019-03-19', '2021-10-08',
                          '2020-06-25', '2018-08-31', '2022-02-14',
                          '2019-05-07', '2021-09-20', '2021-01-10',
                          '2019-12-05', '2018-11-28', '2022-02-14',
                          '2022-11-01', '2023-01-15', '2022-05-20',
                          None, '2020-10-11', '2019-08-03'],
    'ocena_roczna': [4.5, 3.8, None, 4.2, 5.0,
                     3.5, 4.7, None, 4.1, 3.9,
                     5.0, 4.3, 3.6, None, 4.8,
                     3.7, 4.4, 4.9, None, 3.8,
                     None, 4.7, 4.3, 4.9, 5.0,
                     4.6, None, 4.9, 3.5, 4.1]
}

df = pd.DataFrame(data)
print(f"Wczytano dataset: {df.shape[0]} wierszy, {df.shape[1]} kolumn")
df.head(10)

Wczytano dataset: 30 wierszy, 6 kolumn

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0
5,6,Filip,HR,4200,2020-08-14,3.5
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
7,8,HENRYK,it,6900,2021-06-18,NaN
8,9,irena,HR,3500,2017-09-23,4.1
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9

In [18]:
# 1. Wyświetl info() aby zobaczyć typy danych i liczbę wartości non-null
print("=== INFO O DATAFRAME ===")
df.info()

# 2. Policz brakujące wartości w każdej kolumnie
print("\n=== BRAKUJĄCE WARTOŚCI ===")
braki = df.isna().sum()
print(braki)

# 3. Oblicz procent braków per kolumna
print("\n=== PROCENT BRAKÓW (%) ===")
procent_brakow = round(df.isna().sum() / len(df) * 100, 1)
print(procent_brakow)

# 4. Wyświetl wiersze, które mają przynajmniej jeden brak
print("\n=== WIERSZE Z BRAKAMI ===")
wiersze_z_brakami = df[df.isna().any(axis=1)]
print(wiersze_z_brakami)

=== INFO O DATAFRAME ===
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pracownika      30 non-null     int64
 1   imie               30 non-null     str
 2   dzial              30 non-null     str
 3   wynagrodzenie      29 non-null     str
 4   data_zatrudnienia  29 non-null     str
 5   ocena_roczna       24 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.5 KB

=== BRAKUJĄCE WARTOŚCI ===
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        1
data_zatrudnienia    1
ocena_roczna         6
dtype: int64

=== PROCENT BRAKÓW (%) ===
id_pracownika         0.0
imie                  0.0
dzial                 0.0
wynagrodzenie         3.3
data_zatrudnienia     3.3
ocena_roczna         20.0
dtype: float64

=== WIERSZE Z BRAKAMI ===
    id_pracownika     imie     dzial wynagrodzenie data_zatrudnienia  \
2               3   CELINA        HR          3800        2021-01-10
7               8   HENRYK        it          6900        2021-06-18
13             14  norbert        IT          6800        2019-03-19
18             19   Teresa  Sprzedaz          3800        2019-05-07
20              3   CELINA        HR          3800        2021-01-10
26             22   Xawery        IT          5000        2022-05-20
27             23   Yvonne        hr           NaN               NaN

    ocena_roczna
2            NaN
7            NaN
13           NaN
18           NaN
20           NaN
26           NaN
27           4.9

In [19]:
# 1. Sprawdź unikalne wartości w kolumnie wynagrodzenie
print("=== UNIKALNE WARTOŚCI ===")
print(df['wynagrodzenie'].unique())

# 2. Zamień 'brak' na np.nan
df['wynagrodzenie'] = df['wynagrodzenie'].replace('brak', np.nan)

# 3. Konwersja kolumny na float
df['wynagrodzenie'] = pd.to_numeric(
    df['wynagrodzenie'],
    errors='coerce'
)

# Sprawdzenie typu po konwersji
print("\n=== TYP DANYCH ===")
print(df['wynagrodzenie'].dtype)

# 4. Ile NaN jest teraz?
print("\n=== LICZBA NaN ===")
liczba_nan = df['wynagrodzenie'].isna().sum()
print(f"Liczba braków w wynagrodzenie: {liczba_nan}")

# Podgląd kolumny po zmianach
print("\n=== PODGLĄD DANYCH ===")
print(df[['id_pracownika', 'wynagrodzenie']].head(10))

=== UNIKALNE WARTOŚCI ===
<StringArray>
['4500', '6200', '3800', '5100', '7500', '4200', '5800', '6900', '3500',
 '4800', '7200', '4100', '5500', '6800', '3900', '5200', '4700', '6100',
 '5400', 'brak', '5000',    nan, '4300', '6600']
Length: 24, dtype: str

=== TYP DANYCH ===
float64

=== LICZBA NaN ===
Liczba braków w wynagrodzenie: 2

=== PODGLĄD DANYCH ===
   id_pracownika  wynagrodzenie
0              1         4500.0
1              2         6200.0
2              3         3800.0
3              4         5100.0
4              5         7500.0
5              6         4200.0
6              7         5800.0
7              8         6900.0
8              9         3500.0
9             10         4800.0

In [20]:
# 1. Oblicz medianę wynagrodzenia
mediana = df['wynagrodzenie'].median()
print(f"Mediana wynagrodzenia: {mediana}")

# 2. Wypełnij NaN medianą
df['wynagrodzenie'] = df['wynagrodzenie'].fillna(mediana)

# Sprawdzenie efektu
print("\n=== WYNAGRODZENIE PO UZUPEŁNIENIU ===")
print(df['wynagrodzenie'].head(10))

# 3. Oblicz średnią ocena_roczna
srednia = round(df['ocena_roczna'].mean(), 2)
print(f"\nŚrednia ocena roczna: {srednia}")

# 4. Wypełnij NaN średnią
df['ocena_roczna'] = df['ocena_roczna'].fillna(srednia)

# Sprawdzenie efektu
print("\n=== OCENA ROCZNA PO UZUPEŁNIENIU ===")
print(df['ocena_roczna'].head(10))

# 5. Sprawdź ile NaN zostało
print("\n=== POZOSTAŁE BRAKI ===")
print(df.isna().sum())

Mediana wynagrodzenia: 5150.0

=== WYNAGRODZENIE PO UZUPEŁNIENIU ===
0    4500.0
1    6200.0
2    3800.0
3    5100.0
4    7500.0
5    4200.0
6    5800.0
7    6900.0
8    3500.0
9    4800.0
Name: wynagrodzenie, dtype: float64

Średnia ocena roczna: 4.34

=== OCENA ROCZNA PO UZUPEŁNIENIU ===
0    4.50
1    3.80
2    4.34
3    4.20
4    5.00
5    3.50
6    4.70
7    4.34
8    4.10
9    3.90
Name: ocena_roczna, dtype: float64

=== POZOSTAŁE BRAKI ===
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

In [21]:
# 1. Usuń wiersze z brakami w 'data_zatrudnienia'
df_bez_brakow = df.dropna(subset=['data_zatrudnienia'])

# Liczba wierszy po usunięciu braków
print("Liczba wierszy po dropna():")
print(len(df_bez_brakow))

# Dla porównania
print("\nLiczba wierszy przed:")
print(len(df))

Liczba wierszy po dropna():
29

Liczba wierszy przed:
30

In [22]:
# Zacznij od świeżej kopii
df2 = pd.DataFrame(data)  # ta sama definicja 'data' co wyżej

# Najpierw napraw wynagrodzenie (tak samo jak w Ćw. 1b)
df2['wynagrodzenie'] = df2['wynagrodzenie'].replace('brak', np.nan)
df2['wynagrodzenie'] = pd.to_numeric(df2['wynagrodzenie'], errors='coerce')

In [23]:
# 1. Liczba pełnych duplikatów
print("=== PEŁNE DUPLIKATY ===")
print(df2.duplicated().sum())

# 2. Wyświetlenie pełnych duplikatów
print("\n=== ZDUPLIKOWANE WIERSZE ===")
print(df2[df2.duplicated()])

# 3. Duplikaty wg id_pracownika
print("\n=== DUPLIKATY WG ID ===")
print(df2.duplicated(subset=['id_pracownika']).sum())

# 4. Liczba wystąpień każdego ID
print("\n=== LICZBA WYSTĄPIEŃ ID ===")
print(df2['id_pracownika'].value_counts().sort_index())

=== PEŁNE DUPLIKATY ===
5

=== ZDUPLIKOWANE WIERSZE ===
    id_pracownika    imie     dzial  wynagrodzenie data_zatrudnienia  \
20              3  CELINA        HR         3800.0        2021-01-10
21              7   Gosia  Sprzedaz         5800.0        2019-12-05
22             12  Leszek        HR         4100.0        2018-11-28
23             18  sławek        HR         6100.0        2022-02-14
24              5     Ewa        IT         7500.0        2022-11-01

    ocena_roczna
20           NaN
21           4.7
22           4.3
23           4.9
24           5.0

=== DUPLIKATY WG ID ===
5

=== LICZBA WYSTĄPIEŃ ID ===
id_pracownika
1     1
2     1
3     2
4     1
5     2
6     1
7     2
8     1
9     1
10    1
11    1
12    2
13    1
14    1
15    1
16    1
17    1
18    2
19    1
20    1
21    1
22    1
23    1
24    1
25    1
Name: count, dtype: int64

In [24]:
df2 = df2.drop_duplicates().reset_index(drop=True)

print("\n=== NOWY KSZTAŁT DF ===")
print(df2.shape)

=== NOWY KSZTAŁT DF ===
(25, 6)

In [25]:
# 1. Typ przed konwersją
print("\n=== TYP PRZED ===")
print(df2['data_zatrudnienia'].dtype)

# 2. Konwersja na datetime
df2['data_zatrudnienia'] = pd.to_datetime(
    df2['data_zatrudnienia'],
    errors='coerce'
)

=== TYP PRZED ===
str

In [28]:
# Czyszczenie kolumny dzial
df2['dzial'] = df2['dzial'].str.strip().str.title()

# 1. Zatrudnieni od 2021 roku
df2['rok_zatrudnienia'] = df2['data_zatrudnienia'].dt.year
po_2021 = df2[df2['rok_zatrudnienia'] >= 2021]

print("\n=== ZATRUDNIENI OD 2021 ===")
print(len(po_2021))

# 2. Wynagrodzenie > 6000
powyzej_6000 = df2[df2['wynagrodzenie'] > 6000]

print("\n=== WYNAGRODZENIE > 6000 ===")
print(len(powyzej_6000))

# 3. Liczba pracowników w dziale IT
it_count = df2[df2['dzial'] == 'It']

print("\n=== LICZBA PRACOWNIKÓW W IT ===")
print(len(it_count))

=== ZATRUDNIENI OD 2021 ===
10

=== WYNAGRODZENIE > 6000 ===
7

=== LICZBA PRACOWNIKÓW W IT ===
9

In [29]:
import pandas as pd
import numpy as np

df_clean = pd.DataFrame(data)
df_clean.head()

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0

In [30]:
df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].replace('brak', np.nan)

df_clean['wynagrodzenie'] = pd.to_numeric(
    df_clean['wynagrodzenie'],
    errors='coerce'
)

df_clean['wynagrodzenie'].head()

0    4500.0
1    6200.0
2    3800.0
3    5100.0
4    7500.0
Name: wynagrodzenie, dtype: float64

In [31]:
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

df_clean.shape

(25, 6)

In [32]:
mediana = df_clean['wynagrodzenie'].median()

df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].fillna(mediana)

mediana

np.float64(5100.0)

In [33]:
srednia_ocena = round(df_clean['ocena_roczna'].mean(), 2)

df_clean['ocena_roczna'] = df_clean['ocena_roczna'].fillna(srednia_ocena)

srednia_ocena

np.float64(4.26)

In [34]:
df_clean['imie'] = (
    df_clean['imie']
    .str.strip()
    .str.title()
)

df_clean['imie'].head()

0      Anna
1    Bartek
2    Celina
3     Darek
4       Ewa
Name: imie, dtype: str

In [35]:
df_clean['dzial'] = (
    df_clean['dzial']
    .str.strip()
    .str.title()
)

df_clean['dzial'] = df_clean['dzial'].str.replace('Hr', 'HR', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('It', 'IT', regex=False)

df_clean['dzial'].unique()

<StringArray>
['Sprzedaz', 'IT', 'HR']
Length: 3, dtype: str

In [36]:
df_clean['data_zatrudnienia'] = pd.to_datetime(
    df_clean['data_zatrudnienia'],
    errors='coerce'
)

df_clean['data_zatrudnienia'].dtype

dtype('<M8[us]')

In [37]:
print("Shape:", df_clean.shape)

print("\nDtypes:\n", df_clean.dtypes)

print("\nNaN:\n", df_clean.isna().sum())

print("\nDziały:", sorted(df_clean['dzial'].unique()))

print("\nImiona:", df_clean['imie'].tolist()[:8])

Shape: (25, 6)

Dtypes:
 id_pracownika                 int64
imie                            str
dzial                           str
wynagrodzenie               float64
data_zatrudnienia    datetime64[us]
ocena_roczna                float64
dtype: object

NaN:
 id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Działy: ['HR', 'IT', 'Sprzedaz']

Imiona: ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa', 'Filip', 'Gosia', 'Henryk']